### ISSUE TITLE
Self scoring submission doesn't update total round time correctly

### ISSUE THREAD

**Issue by paul4477** [timtraver/rcvault#11]
If I submit (not sure if its significant, but the scenario here was with a time already submitted - so I'm really editing a time) a flight time (example done with event 2051, round 3) through the self scoring interface then when I view the round summary: https://www.f3xvault.com/?action=event&function=event_round_edit&event_id=2051&event_round_id=15470
then the Total time is incorrect.
On first submission the minutes are correct. On second submission this appears to set the seconds correctly and at no point do the tenths of a second get set correctly.
Submitting the same values through the editable round page does not have the same behaviour.
After editing the flight time through the round page I don't seem to be able to successfully submit the score through the self scoring page again (self-score locked is not ticked).

**Comment by timtraver** [comment]
Found and fixed the issue.
