### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by mikejr83** [timtraver/rcvault#2]
This is the repository for http://www.f3xvault.com?

I'm working on a scoring application and was hoping to be able to post the scores to the vault as the contest went on. Are there any endpoints for external applications to post data? I know there is the CSV import on the site but it would be extra neat if I could post JSON data (or XML) to create and update an in progress contest.

Thanks!

**Comment by timtraver** [comment]
Hi Mike,

Yes, that is the repository that I use for the software.

I currently do not have an API made for the system yet, but its on the near
term todo list, because I have other people writing software for timing
devices that need it.

But yes, I will be working on that.

Tim

**Comment by mikejr83** [comment]
Thanks for the info. I'll keep this "issue" tagged so that whenever the API feature goes live (and you resolve this) I can start working on my app's end. 

Thanks for the cool site!

**Comment by timtraver** [comment]
Mike,

Just wanted to let you know that I do now have an official API to f3xvault. You can find the docs at http://www.f3xvault.com/?action=api_docs

t
