### ISSUE TITLE
Self scoring glitch on bad input

### ISSUE THREAD

**Issue by paul4477** [timtraver/rcvault#20]
Using event ID 1855, round 1 (task B), entering the following times (for pilot Darth vader):
7:58.6
9:23.2
results in those being auto-corrected to 4:58.6 and 4:23.2
whilst that's not perfect, the main issue is that on submission, the minute field for both is set to zero, resulting in submitted times of:
0:58.6
0:23.2

**Comment by paul4477** [comment]
Replicated in the next round as well so seem perhaps to be independent of task.
If the time has previously been submitted (with a valid value) then the beahviour is different. It reverts back to the valid time, perhaps suggesting that the code is reverting to the saved value in some case rather than setting explicitly to zero...?

**Comment by timtraver** [comment]
Newer system of correcting individual flights is in place, as well as an overall time check before submission.
