### ISSUE TITLE
Self scoring - Poker

### ISSUE THREAD

**Issue by paul4477** [timtraver/rcvault#21]
![image](https://user-images.githubusercontent.com/60312505/166651400-211276cd-d2d4-4de3-8d2d-45da1bde7e2f.png)
Total time in excess of 10 minutes.

**Comment by timtraver** [comment]
Fixed this by calculating total round time entry and giving error. Although in this case, the individual flight times cannot be checked on the fly because I do not know what the max time of a single flight is (besides 9:59). I am going to close this for now.
